import React from 'react';
import { HlsPlayer } from '../../components';

export const HomePage = () => {
  return (
    <div>
      <p>Homepage</p>
      <HlsPlayer />
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
      <p>homepage</p>
    </div>
  );
};
